//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuristProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuristData
    {
        public int TuristDataId { get; set; }
        public int TuristDataType { get; set; }
        public int CompanyId { get; set; }
        public decimal Residence { get; set; }
        public decimal Food { get; set; }
        public decimal Transportation { get; set; }
        public decimal Excursion { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
